Lesson 37 (Board)
Dmiytriy/diploma_todo pull request #3
Opened 2023-04-09 18:08 UTC by Dmiytriy

2023-04-10 08:05 UTC, painassasin requested changes

2023-04-10 08:05 UTC, painassasin commented on todolist/goals/models.py
> +class BoardParticipant(Board):
Тут наследование должно быть от `BaseModel`

2023-04-10 08:05 UTC, painassasin commented on todolist/goals/models.py
> +        Board, verbose_name='Доска', on_delete=models.PROTECT, related_name='categories', null=True
`null=True` нужно удалить - у категории обязательно должна быть доска

2023-04-11 18:36 UTC, Dmiytriy commented on todolist/goals/models.py
> +class BoardParticipant(Board):
изменил наследование, снес базу

2023-04-12 09:13 UTC, painassasin approved these changes

2023-04-13 15:20 UTC, merged